package edu.remad.tutoring2.appconstants;

public final class DataSourcesAppConstants {

	private DataSourcesAppConstants() {
	}

	public static final String DATA_SOURCES_MYSQL_URL = "TUTOR_DATA_SOURCES_MYSQL_URL";
	public static final String DATA_SOURCES_MYSQL_USERNAME = "TUTOR_DATA_SOURCES_MYSQL_USERNAME";
	public static final String DATA_SOURCES_MYSQL_PASSWORD = "TUTOR_DATA_SOURCES_MYSQL_PASSWORD";
	public static final String DEVELOPMENT_DATA_SOURCES_MYSQL_URL = "TUTOR_DEVELOPMENT_DATA_SOURCES_MYSQL_URL";
	public static final String DEVELOPMENT_DATA_SOURCES_MYSQL_USERNAME = "TUTOR_DEVELOPMENT_DATA_SOURCES_MYSQL_USERNAME";
	public static final String DEVELOPMENT_DATA_SOURCES_MYSQL_PASSWORD = "TUTOR_DEVELOPMENT_DATA_SOURCES_MYSQL_PASSWORD";
}
